#!/usr/bin/env bash

# A lot of this is from mathias bynens osx dotfile http://mths.be/osx

# Ask for the administrator password upfront
sudo -v

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400

# Restart automatically if the computer freezes
systemsetup -setrestartfreeze on

###############################################################################
# SSD-specific tweaks                                                         #
###############################################################################

# Backing up to Amazon cloud, no need to have another backup to SSD
# Disable local Time Machine snapshots
sudo tmutil disablelocal

# Disable hibernation (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

# Remove the sleep image file to save disk space
sudo rm /Private/var/vm/sleepimage
# Create a zero-byte file instead…
sudo touch /Private/var/vm/sleepimage
# …and make sure it can’t be rewritten
sudo chflags uchg /Private/var/vm/sleepimage

###############################################################################
# Screen                                                                      #
###############################################################################

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

###############################################################################
# Finder                                                                      #
###############################################################################

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Show the ~/Library folder
chflags nohidden ~/Library


###############################################################################
# BBEdit                                                                      #
###############################################################################

#adjust default completion interval for BBEdit autocomplete
defaults write com.barebones.bbedit Editor_AutoCompleteDelay -float 0.7

# To enable BBEdit to search for .p4config file if perforce working
# directory is located on a remote MacFUSE volume
defaults write com.barebones.bbedit DisableP4ConfigScanOnRemoteVolumes -bool NO

# Make sure ctags work on a directory by directory basis on remote MacFUSE volumes
defaults write com.barebones.bbedit DisableCtagsScanOnRemoteVolumes -bool NO

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "cfprefsd" "Finder" "SystemUIServer" "BBEdit"  ; do
	killall "${app}" > /dev/null 2>&1
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
